version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://usuario:secret_pass@db:5432/panaderia
    depends_on:
      - db

  
  
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=secret_pass
      - POSTGRES_DB=panaderia
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
